### ISSUE TITLE
No issues? 

### ISSUE THREAD

**Issue by prashantbarca** [ceg-website/ceg_annauniv_edu#1]

**Comment by Mithul** [comment]
That's an issue ?

**Comment by prashantbarca** [comment]
Of course! There are issues all over!

**Comment by senthil-ramasamy** [comment]
The people at the office couldn't handle ruby on rails and due to other management issues, we have shifted the whole thing to PHP ( The code of which is in BitBucket ). This repo is no longer maintained, if anyone of CEG family in the future wants to change or something, they could use this as a starting point if they find it useful. Sorry for the delayed reply @prashantbarca @Mithul didnt notice there was an issue opened.
